### ISSUE TITLE
Axios Request Failed with HTTP Status Code 403

### ISSUE THREAD

**Issue by karlhorky** [richartkeil/notion-guardian#11]
Hi @richartkeil 👋 Hope you are well.

Recently, our daily Notion backups (using our [`notion-backup`](https://github.com/upleveled/notion-backup) fork of `notion-guardian`) started failing with an HTTP 403 status code:

```
AxiosError: Request failed with status code 403
```

We have had no code changes in the last 5 days, and the daily backups have succeeded until today (eg. yesterday's backup succeeded).

I originally also tried updating the token (which I thought was the problem originally) but this did not change the error.

Relevant request details (sanitized):

```
request: ClientRequest {
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    Cookie: 'token_v2=***',
    'User-Agent': 'axios/1.3.4',
    'Accept-Encoding': 'gzip, compress, deflate, br'
  },
  protocol: 'https:',
  hostname: 'file.notion.so',
  path: '/f/t/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/Export-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx.zip?id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx&table=user_export&expirationTimestamp=1680167194467&signature=xxxxxxxxxx_xxxxxxxx-xxxxxxxxxxxxxxxxxx&download=true&downloadName=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx%2FExport-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx.zip',
  baseURL: 'https://www.notion.so/api/v3',
}
```

And response details:

```
   response: {
     status: 403,
     statusText: 'Forbidden',
```

And `axios` config:

```
  config: {
    baseURL: 'https://www.notion.so/api/v3',
    method: 'get',
    url: 'https://file.notion.so//f/t/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/Export-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx.zip?id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx&table=user_export&expirationTimestamp=1680167194467&signature=xxxxxxxxxx_xxxxxxxx-xxxxxxxxxxxxxxxxxx&download=true&downloadName=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx%2FExport-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx.zip',
    responseType: 'stream',
    data: undefined
  },
```

I'm guessing because of the `responseType: 'stream'` in the error message, it probably has to do with this code here:

https://github.com/richartkeil/notion-guardian/blob/80135acc1e4dc2b9b6560c48095f17c1c7895573/index.js#L72-L76

---

Maybe Notion changed their internal API?

**Comment by Tsunamicloud** [comment]
I'm having the exact same issue. ToT

**Comment by karlhorky** [comment]
I'm guessing because of the `responseType: 'stream'` in the error message, it probably has to do with this code here:

https://github.com/richartkeil/notion-guardian/blob/80135acc1e4dc2b9b6560c48095f17c1c7895573/index.js#L72-L76

Also added this to the issue description above

**Comment by karlhorky** [comment]
Looks like it's a missing cookie:

- https://github.com/upleveled/notion-backup/pull/205

I think @Josehower will do a PR here too.

**Comment by Josehower** [comment]
I created a PR for this issue https://github.com/richartkeil/notion-guardian/pull/12

**Comment by richartkeil** [comment]
Hey @karlhorky and @Josehower thanks for looking into this, and especially for the PR! I'll merge it.
