### ISSUE TITLE
Export not unzipped?

### ISSUE THREAD

**Issue by fortran01** [richartkeil/notion-guardian#14]
Did I miss anything? It's the ZIP file that is committed. I have to do the following to unzip. 🙏🏽

```
          # Find the zip file using the wildcard
          zip_file="$(ls *.zip | head -n1)"
          # Unzip the file
          unzip "$zip_file"
          # Get the top-level folder
          folder=$(unzip -Z1 "$zip_file" | awk -F/ '{print $1}' | sort | uniq)
          # Move the contents of the first-level folder to the current directory
          rsync "${folder%/}"/* .
          # Remove the first-level folder
          rm -r "${folder%/}"
          # Delete the zip file
          rm "$zip_file"
```

**Comment by richartkeil** [comment]
Have you altered the script in some way? Usually these two lines extract the .zip and remove it afterwards:

```js
// ...
await extract(workspaceZip, { dir: workspaceDir });
await unlink(workspaceZip);
// ...
  ```

Also `workspace.zip` is in the `.gitignore` which prevents it from being committed.

Edit: I suspect this might be because of #10 → I'll have a look at it.

**Comment by fortran01** [comment]
No modifications. I have to do above, so I can unzip it. Some observations:

- my output file is less than 500MB
- the file name is not workspace.zip, it's some hash

Thanks for checking.

**Comment by heibaikn** [comment]
I encountered the same issue
I believe the reason is that when calling notion exportURL, it returns a zip package. The `exportFromNotion` function compresses the zip package again.
```
const stream = response.data.pipe(createWriteStream(destination));
```

My solution is to use the onEntry property of extract to detect and unzip the zip package again. The code looks like this:
```
  await extract(workspaceZip, {
    dir: workspaceDir, onEntry: async (entry, zipfile) => {
      if (entry.fileName.toLowerCase().endsWith('.zip')) {
        const nestedZipFile = join(workspaceDir, entry.fileName);
        zipfile.openReadStream(entry, (err, readStream) => {
          if (err) throw err;
          const writeStream = createWriteStream(nestedZipFile);
          readStream.pipe(writeStream);
          writeStream.on('finish', () => {
            extract(nestedZipFile, { dir: workspaceDir })
          });
        });
      }
    }
  });
```

**Comment by richartkeil** [comment]
This problem should be fixed now. Thank you @heibaikn for the PR (#17)! I tried using your approach, however it did not work when I tested it with a large export (~1GB), so I fell back to another solution and used the opportunity to clean up the repo a bit.
