### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by karlhorky** [richartkeil/notion-guardian#3]
Hey @richartkeil, just wanted to ping you that I've finished my improvements to the script:

1. Export from blocks instead of entire workspace (with `recursive` option)
2. Switch to ESM, top-level `await`
3. Change forking workflow to template workflow, simplify instructions
4. Commit to same repo instead of an external one

https://github.com/upleveled/notion-backup

Feel free to take anything that is useful! (and close this issue whenever you like)  Happy to answer any questions too.

Credited you at the bottom too, because your script proved to be a great basis for writing this.

**Comment by richartkeil** [comment]
Hey @karlhorky, thanks for improving the tool! I just got around to look into it again and your fixes were really helpful. I also added a mention pointing to your repository for users who prefer the same-repo solution :)

**Comment by karlhorky** [comment]
Nice, glad they were helpful! Thanks for the mention!

**Comment by karlhorky** [comment]
Btw I've been keeping this up to date (latest dependencies, etc), and I also switched to TypeScript:

https://github.com/upleveled/notion-backup
