### ISSUE TITLE
The job running on runner Hosted Agent has exceeded the maximum execution time of 15 minutes.

### ISSUE THREAD

**Issue by thedavidweng** [richartkeil/notion-guardian#6]
The export is working, but the action seems to have set the wait time too short.

**Comment by thedavidweng** [comment]
I extended the wait time, now it shows "Error: Process completed with exit code 1."

**Comment by pratheekbhandary** [comment]
Facing same issue - any fix?

**Comment by richartkeil** [comment]
Sorry for the long response time, can you provide a complete error log? I could not reproduce the issue so far.
