### ISSUE TITLE
Invalid workflow file - how to add secret?

### ISSUE THREAD

**Issue by pooriaarab** [richartkeil/notion-guardian#7]
Hi, 

![image](https://user-images.githubusercontent.com/42897904/175427926-bc5b134c-5181-4d14-800a-7202a0daea11.png)

Wondering if the notion token, space id, user id should come directly after "secrets." and replace SPACE_ID or am I missing something?

**Comment by richartkeil** [comment]
I'm not sure if I can follow you. The space ID of your Notion workspace should be stored in a secret named `NOTION_SPACE_ID`, which is then passed to the script through the backup workflow file. Does that help?
