### ISSUE TITLE
Unexpected Symbol

### ISSUE THREAD

**Issue by shivaAcharya** [richartkeil/notion-guardian#8]
![image](https://user-images.githubusercontent.com/26162009/187053851-3329a533-3cfc-4973-a593-c60ac802ff10.png)

Not sure what this error means. I am trying it for the first time. I have Notion Space ID as NOTION_SPACE_ID : ${{ secrets.25................. }}.

Am I supposed to enter the ID differently?

**Comment by richartkeil** [comment]
It looks like the name of your secret is your Notion Space ID. The name should literally be `NOTION_SPACE_ID`, while the value is the actual space ID you obtained.
