### ISSUE TITLE
Error: Request failed with status code 502

### ISSUE THREAD

**Issue by pratheekbhandary** [richartkeil/notion-guardian#9]
Used to work like a charm, but encountering the below issue now. Any leads would be appreciated 🙏🏻.
![image](https://user-images.githubusercontent.com/30550942/190870138-1b09f5b1-4d8b-49f8-a688-f154916581b7.png)

**Comment by richartkeil** [comment]
A 502 bad gateway error is usually caused on the server side or some intermediate proxy. Does the error occur all the time? If not, a simple retry might already help.
